/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ewu.event.system;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddAdmin() {
   setContentPane(new BackgroundPanel());
initComponents();
    setSize(900, 600);
    setLocationRelativeTo(null);
    setResizable(false);


    // Only a logged-in Admin may access this screen
    if (Session.role == null || !Session.role.equalsIgnoreCase("Admin")) {

        JOptionPane.showMessageDialog(
                this,
                "Access Denied. Admin authorization required."
        );

        LoginForm login = new LoginForm();
        login.setLocationRelativeTo(null);
        login.setVisible(true);

        this.dispose();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkShowPasswords = new javax.swing.JCheckBox();
        btnAddAdmin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW ADMIN");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password:");

        chkShowPasswords.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkShowPasswords.setText("Show Passwords");
        chkShowPasswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPasswordsActionPerformed(evt);
            }
        });

        btnAddAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddAdmin.setText("ADD ADMIN ");
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addComponent(chkShowPasswords))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btnAddAdmin)
                        .addGap(72, 72, 72)
                        .addComponent(btnBack)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(chkShowPasswords))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAdmin)
                    .addComponent(btnBack))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void chkShowPasswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordsActionPerformed
       if (chkShowPasswords.isSelected()) {

    txtPassword.setEchoChar((char) 0);
    txtConfirmPassword.setEchoChar((char) 0);

} else {

    txtPassword.setEchoChar('*');
    txtConfirmPassword.setEchoChar('*');
}
    }//GEN-LAST:event_chkShowPasswordsActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
       String name = txtName.getText().trim();
String email = txtEmail.getText().trim().toLowerCase();

String password =
        new String(txtPassword.getPassword());

String confirmPassword =
        new String(txtConfirmPassword.getPassword());


// REQUIRED FIELDS
if (name.isEmpty()
        || email.isEmpty()
        || password.isEmpty()
        || confirmPassword.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Please fill in all fields."
    );

    return;
}


// NAME CHECK
if (name.length() < 3) {

    JOptionPane.showMessageDialog(
            this,
            "Please enter the administrator's full name."
    );

    return;
}


// EMAIL CHECK
if (!email.matches(
        "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"
)) {

    JOptionPane.showMessageDialog(
            this,
            "Please enter a valid email address."
    );

    return;
}


// STRONGER ADMIN PASSWORD
if (password.length() < 8) {

    JOptionPane.showMessageDialog(
            this,
            "Admin password must contain at least 8 characters."
    );

    return;
}

if (!password.matches(".*[A-Z].*")) {

    JOptionPane.showMessageDialog(
            this,
            "Admin password must contain an uppercase letter."
    );

    return;
}

if (!password.matches(".*[a-z].*")) {

    JOptionPane.showMessageDialog(
            this,
            "Admin password must contain a lowercase letter."
    );

    return;
}

if (!password.matches(".*\\d.*")) {

    JOptionPane.showMessageDialog(
            this,
            "Admin password must contain a number."
    );

    return;
}


// CONFIRM PASSWORD
if (!password.equals(confirmPassword)) {

    JOptionPane.showMessageDialog(
            this,
            "Passwords do not match."
    );

    return;
}


int confirm = JOptionPane.showConfirmDialog(
        this,
        "Appoint " + name + " as a new administrator?",
        "Confirm Admin Appointment",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}


try {

    Connection con = DBConnection.getConnection();

    if (con == null) {

        JOptionPane.showMessageDialog(
                this,
                "Database connection failed."
        );

        return;
    }


    // CHECK DUPLICATE EMAIL
    String checkSql =
            "SELECT user_id FROM users WHERE email=?";

    PreparedStatement check =
            con.prepareStatement(checkSql);

    check.setString(1, email);

    ResultSet rs = check.executeQuery();

    if (rs.next()) {

        JOptionPane.showMessageDialog(
                this,
                "An account already exists with this email."
        );

        rs.close();
        check.close();
        con.close();

        return;
    }

    rs.close();
    check.close();


    // CREATE ADMIN
    String sql =
            "INSERT INTO users "
            + "(name, student_id, email, password, role, club, account_status) "
            + "VALUES (?, NULL, ?, ?, 'Admin', NULL, 'Active')";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setString(1, name);
    pst.setString(2, email);
    pst.setString(3, password);

    pst.executeUpdate();

    pst.close();
    con.close();


    JOptionPane.showMessageDialog(
            this,
            "New Administrator Appointed Successfully!"
    );


    ManageUsers manage =
            new ManageUsers();

    manage.setLocationRelativeTo(null);
    manage.setVisible(true);

    this.dispose();


} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );

    e.printStackTrace();
}
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
ManageUsers manage =
        new ManageUsers();

manage.setLocationRelativeTo(null);
manage.setVisible(true);

this.dispose();    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox chkShowPasswords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
