/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ewu.event.system;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
    setContentPane(new BackgroundPanel());
initComponents();
        setSize(900, 600);
    setLocationRelativeTo(null);
    setResizable(false);

    if (Session.userId == 0 || Session.role == null) {

        JOptionPane.showMessageDialog(
                this,
                "Please login first."
        );

        LoginForm login = new LoginForm();
        login.setVisible(true);

        this.dispose();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCurrentPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        chkShowPasswords = new javax.swing.JCheckBox();
        btnChangePassword = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Password:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm New Password:");

        chkShowPasswords.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkShowPasswords.setForeground(new java.awt.Color(255, 255, 255));
        chkShowPasswords.setText("Show Passwords");
        chkShowPasswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPasswordsActionPerformed(evt);
            }
        });

        btnChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangePassword.setText("CHANGE PASSWORD ");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCurrentPassword)
                            .addComponent(txtNewPassword)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(chkShowPasswords))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnChangePassword)
                        .addGap(72, 72, 72)
                        .addComponent(btnBack)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCurrentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkShowPasswords))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword)
                    .addComponent(btnBack))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
       String currentPassword =
        new String(txtCurrentPassword.getPassword());

String newPassword =
        new String(txtNewPassword.getPassword());

String confirmPassword =
        new String(txtConfirmPassword.getPassword());


// EMPTY FIELD CHECK
if (currentPassword.isEmpty()
        || newPassword.isEmpty()
        || confirmPassword.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Please fill in all password fields."
    );

    return;
}


// NEW PASSWORD MUST MATCH CONFIRMATION
if (!newPassword.equals(confirmPassword)) {

    JOptionPane.showMessageDialog(
            this,
            "New passwords do not match."
    );

    return;
}


// NEW PASSWORD CANNOT BE SAME AS OLD PASSWORD
if (newPassword.equals(currentPassword)) {

    JOptionPane.showMessageDialog(
            this,
            "New password cannot be the same as your current password."
    );

    return;
}


// BASIC LENGTH RULE
if (newPassword.length() < 8) {

    JOptionPane.showMessageDialog(
            this,
            "New password must contain at least 8 characters."
    );

    return;
}


// STUDENT PASSWORD RULE
if (Session.role.equalsIgnoreCase("Student")) {

    if (!newPassword.matches(".*[A-Za-z].*")
            || !newPassword.matches(".*\\d.*")) {

        JOptionPane.showMessageDialog(
                this,
                "Student password must contain at least one letter and one number."
        );

        return;
    }
}


// ADMIN PASSWORD RULE
if (Session.role.equalsIgnoreCase("Admin")) {

    if (!newPassword.matches(".*[A-Z].*")) {

        JOptionPane.showMessageDialog(
                this,
                "Admin password must contain an uppercase letter."
        );

        return;
    }

    if (!newPassword.matches(".*[a-z].*")) {

        JOptionPane.showMessageDialog(
                this,
                "Admin password must contain a lowercase letter."
        );

        return;
    }

    if (!newPassword.matches(".*\\d.*")) {

        JOptionPane.showMessageDialog(
                this,
                "Admin password must contain a number."
        );

        return;
    }
}


try {

    Connection con = DBConnection.getConnection();

    if (con == null) {

        JOptionPane.showMessageDialog(
                this,
                "Database connection failed."
        );

        return;
    }


    // VERIFY CURRENT PASSWORD
    String checkSql =
            "SELECT user_id FROM users "
            + "WHERE user_id=? AND password=?";

    PreparedStatement check =
            con.prepareStatement(checkSql);

    check.setInt(1, Session.userId);
    check.setString(2, currentPassword);

    ResultSet rs =
            check.executeQuery();


    if (!rs.next()) {

        JOptionPane.showMessageDialog(
                this,
                "Current password is incorrect."
        );

        rs.close();
        check.close();
        con.close();

        txtCurrentPassword.setText("");

        return;
    }


    rs.close();
    check.close();


    // UPDATE PASSWORD
    String updateSql =
            "UPDATE users SET password=? WHERE user_id=?";

    PreparedStatement update =
            con.prepareStatement(updateSql);

    update.setString(1, newPassword);
    update.setInt(2, Session.userId);

    int rows =
            update.executeUpdate();

    update.close();
    con.close();


    if (rows > 0) {

        JOptionPane.showMessageDialog(
                this,
                "Password Changed Successfully!"
        );

        txtCurrentPassword.setText("");
        txtNewPassword.setText("");
        txtConfirmPassword.setText("");

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Password could not be changed."
        );
    }


} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );

    e.printStackTrace();
}
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void chkShowPasswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordsActionPerformed
       if (chkShowPasswords.isSelected()) {

    txtCurrentPassword.setEchoChar((char) 0);
    txtNewPassword.setEchoChar((char) 0);
    txtConfirmPassword.setEchoChar((char) 0);

} else {

    txtCurrentPassword.setEchoChar('*');
    txtNewPassword.setEchoChar('*');
    txtConfirmPassword.setEchoChar('*');
}
    }//GEN-LAST:event_chkShowPasswordsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       if (Session.role != null
        && Session.role.equalsIgnoreCase("Admin")) {

    AdminDashboard admin =
            new AdminDashboard();

    admin.setLocationRelativeTo(null);
    admin.setVisible(true);

} else {

    StudentDashboard student =
            new StudentDashboard();

    student.setLocationRelativeTo(null);
    student.setVisible(true);
}

this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JCheckBox chkShowPasswords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtCurrentPassword;
    private javax.swing.JPasswordField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
