/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ewu.event.system;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
    setContentPane(new BackgroundPanel());
initComponents();
    setSize(900, 600);
    setLocationRelativeTo(null);
    setResizable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSubmitRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnResetApproved = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ForgotPassword");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registered Email:");

        btnSubmitRequest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmitRequest.setText("SUBMIT RESET REQUEST ");
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("BACK TO LOGIN");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnResetApproved.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnResetApproved.setText("RESET APPROVED PASSWORD");
        btnResetApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetApprovedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(528, 528, 528))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentId)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(373, 373, 373))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmitRequest)
                        .addGap(68, 68, 68)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnResetApproved)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitRequest)
                    .addComponent(btnBack))
                .addGap(69, 69, 69)
                .addComponent(btnResetApproved)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        String studentId = txtStudentId.getText().trim();
String email = txtEmail.getText().trim().toLowerCase();


// EMPTY CHECK
if (studentId.isEmpty() || email.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Please enter your Student ID and registered email."
    );

    return;
}


// STUDENT ID FORMAT
if (!studentId.matches("\\d{4}-\\d-\\d{2}-\\d{3}")) {

    JOptionPane.showMessageDialog(
            this,
            "Invalid Student ID format.\nExample: 2024-3-60-308"
    );

    return;
}


try {

    Connection con = DBConnection.getConnection();

    if (con == null) {

        JOptionPane.showMessageDialog(
                this,
                "Database connection failed."
        );

        return;
    }


    // FIND THE STUDENT
    String userSql =
            "SELECT user_id, account_status "
            + "FROM users "
            + "WHERE student_id=? "
            + "AND email=? "
            + "AND role='Student'";

    PreparedStatement userCheck =
            con.prepareStatement(userSql);

    userCheck.setString(1, studentId);
    userCheck.setString(2, email);

    ResultSet userResult =
            userCheck.executeQuery();


    if (!userResult.next()) {

        JOptionPane.showMessageDialog(
                this,
                "Student ID and email do not match any student account."
        );

        userResult.close();
        userCheck.close();
        con.close();

        return;
    }


    int userId =
            userResult.getInt("user_id");

    String accountStatus =
            userResult.getString("account_status");

    userResult.close();
    userCheck.close();


    // INACTIVE ACCOUNT CHECK
    if (accountStatus.equalsIgnoreCase("Inactive")) {

        JOptionPane.showMessageDialog(
                this,
                "This account is inactive.\n"
                + "Please contact an administrator."
        );

        con.close();
        return;
    }


    // CHECK FOR EXISTING REQUEST
    String requestCheckSql =
            "SELECT request_id, status "
            + "FROM password_reset_requests "
            + "WHERE user_id=? "
            + "AND status IN ('Pending', 'Approved')";

    PreparedStatement requestCheck =
            con.prepareStatement(requestCheckSql);

    requestCheck.setInt(1, userId);

    ResultSet requestResult =
            requestCheck.executeQuery();


    if (requestResult.next()) {

        String status =
                requestResult.getString("status");

        JOptionPane.showMessageDialog(
                this,
                "You already have a password reset request.\n"
                + "Current Status: " + status
        );

        requestResult.close();
        requestCheck.close();
        con.close();

        return;
    }


    requestResult.close();
    requestCheck.close();


    // CREATE NEW RESET REQUEST
    String insertSql =
            "INSERT INTO password_reset_requests "
            + "(user_id, status) "
            + "VALUES (?, 'Pending')";

    PreparedStatement insert =
            con.prepareStatement(insertSql);

    insert.setInt(1, userId);

    insert.executeUpdate();

    insert.close();
    con.close();


    JOptionPane.showMessageDialog(
            this,
            "Password reset request submitted successfully!\n"
            + "An administrator must approve the request."
    );


    txtStudentId.setText("");
    txtEmail.setText("");


} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );

    e.printStackTrace();
}
    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       LoginForm login = new LoginForm();
login.setLocationRelativeTo(null);
login.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnResetApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetApprovedActionPerformed
ResetPassword reset = new ResetPassword();
reset.setLocationRelativeTo(null);
reset.setVisible(true);

this.dispose();    }//GEN-LAST:event_btnResetApprovedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnResetApproved;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
