/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ewu.event.system;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ManageUsers extends javax.swing.JFrame {

    
   public ManageUsers() {
   setContentPane(new BackgroundPanel());
initComponents();
    setSize(900, 600);
    setLocationRelativeTo(null);
    setResizable(false);

    loadUsers();
}
   private void loadUsers() {

    DefaultTableModel model =
            (DefaultTableModel) tblUsers.getModel();

    model.setRowCount(0);

    String sql =
            "SELECT user_id, name, student_id, email, role, club, account_status "
            + "FROM users ORDER BY role, name";

    try {

        Connection con = DBConnection.getConnection();

        if (con == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Database connection failed."
            );

            return;
        }

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        while (rs.next()) {

            Object[] row = {
                rs.getInt("user_id"),
                rs.getString("name"),
                rs.getString("student_id"),
                rs.getString("email"),
                rs.getString("role"),
                rs.getString("club"),
                rs.getString("account_status")
            };

            model.addRow(row);
        }

        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error loading users: " + e.getMessage()
        );

        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnSuspend = new javax.swing.JButton();
        btnReactivate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        btnAddAdmin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE USERS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search:");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnrefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Student ID", "Email", "Role", "Club", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        btnSuspend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuspend.setText("SUSPEND");
        btnSuspend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspendActionPerformed(evt);
            }
        });

        btnReactivate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReactivate.setText("REACTIVATE");
        btnReactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactivateActionPerformed(evt);
            }
        });

        btnDeactivate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeactivate.setText("DEACTIVATE");
        btnDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateActionPerformed(evt);
            }
        });

        btnAddAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddAdmin.setText("ADD ADMIN ");
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)
                                .addGap(18, 18, 18)
                                .addComponent(btnrefresh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSuspend)
                                .addGap(18, 18, 18)
                                .addComponent(btnReactivate)
                                .addGap(49, 49, 49)
                                .addComponent(btnDeactivate)
                                .addGap(52, 52, 52)
                                .addComponent(btnAddAdmin)
                                .addGap(30, 30, 30)
                                .addComponent(btnBack))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnrefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReactivate)
                    .addComponent(btnDeactivate)
                    .addComponent(btnAddAdmin)
                    .addComponent(btnBack)
                    .addComponent(btnSuspend))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
      AddAdmin addAdmin = new AddAdmin();
addAdmin.setLocationRelativeTo(null);
addAdmin.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       String keyword = txtSearch.getText().trim();

DefaultTableModel model =
        (DefaultTableModel) tblUsers.getModel();

model.setRowCount(0);

String sql =
        "SELECT user_id, name, student_id, email, role, club, account_status "
        + "FROM users "
        + "WHERE name LIKE ? "
        + "OR student_id LIKE ? "
        + "OR email LIKE ? "
        + "ORDER BY role, name";

try {

    Connection con = DBConnection.getConnection();

    PreparedStatement pst =
            con.prepareStatement(sql);

    String searchValue = "%" + keyword + "%";

    pst.setString(1, searchValue);
    pst.setString(2, searchValue);
    pst.setString(3, searchValue);

    ResultSet rs = pst.executeQuery();

    while (rs.next()) {

        Object[] row = {
            rs.getInt("user_id"),
            rs.getString("name"),
            rs.getString("student_id"),
            rs.getString("email"),
            rs.getString("role"),
            rs.getString("club"),
            rs.getString("account_status")
        };

        model.addRow(row);
    }

    rs.close();
    pst.close();
    con.close();

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Search Error: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        txtSearch.setText("");
loadUsers();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnSuspendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspendActionPerformed
        int row = tblUsers.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(
            this,
            "Please select a user first."
    );
    return;
}

int userId = Integer.parseInt(
        tblUsers.getValueAt(row, 0).toString()
);

String role = tblUsers.getValueAt(row, 4).toString();
String status = tblUsers.getValueAt(row, 6).toString();

if (!role.equalsIgnoreCase("Student")) {
    JOptionPane.showMessageDialog(
            this,
            "Admin accounts cannot be suspended here."
    );
    return;
}

if (status.equalsIgnoreCase("Suspended")) {
    JOptionPane.showMessageDialog(
            this,
            "This student is already suspended."
    );
    return;
}

if (status.equalsIgnoreCase("Inactive")) {
    JOptionPane.showMessageDialog(
            this,
            "Inactive accounts cannot be suspended."
    );
    return;
}

int confirm = JOptionPane.showConfirmDialog(
        this,
        "Suspend this student account?",
        "Confirm Suspension",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}

try {

    Connection con = DBConnection.getConnection();

    String sql =
            "UPDATE users SET account_status='Suspended' "
            + "WHERE user_id=? AND role='Student'";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1, userId);

    pst.executeUpdate();

    pst.close();
    con.close();

    JOptionPane.showMessageDialog(
            this,
            "Student account suspended."
    );

    loadUsers();

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnSuspendActionPerformed

    private void btnReactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactivateActionPerformed
       int row = tblUsers.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(
            this,
            "Please select a user first."
    );
    return;
}

int userId = Integer.parseInt(
        tblUsers.getValueAt(row, 0).toString()
);

String role = tblUsers.getValueAt(row, 4).toString();
String status = tblUsers.getValueAt(row, 6).toString();

if (!role.equalsIgnoreCase("Student")) {
    JOptionPane.showMessageDialog(
            this,
            "Admin accounts cannot be modified here."
    );
    return;
}

if (status.equalsIgnoreCase("Active")) {
    JOptionPane.showMessageDialog(
            this,
            "This student account is already active."
    );
    return;
}

int confirm = JOptionPane.showConfirmDialog(
        this,
        "Reactivate this student account?",
        "Confirm Reactivation",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}

try {

    Connection con = DBConnection.getConnection();

    String sql =
            "UPDATE users SET account_status='Active' "
            + "WHERE user_id=? AND role='Student'";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1, userId);

    pst.executeUpdate();

    pst.close();
    con.close();

    JOptionPane.showMessageDialog(
            this,
            "Student account reactivated."
    );

    loadUsers();

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnReactivateActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
       int row = tblUsers.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(
            this,
            "Please select a user first."
    );
    return;
}

int userId = Integer.parseInt(
        tblUsers.getValueAt(row, 0).toString()
);

String role = tblUsers.getValueAt(row, 4).toString();
String status = tblUsers.getValueAt(row, 6).toString();

if (!role.equalsIgnoreCase("Student")) {
    JOptionPane.showMessageDialog(
            this,
            "Admin accounts cannot be deactivated here."
    );
    return;
}

if (status.equalsIgnoreCase("Inactive")) {
    JOptionPane.showMessageDialog(
            this,
            "This account is already inactive."
    );
    return;
}

int confirm = JOptionPane.showConfirmDialog(
        this,
        "Deactivate this student account?\n"
        + "The student's data will remain in the database.",
        "Confirm Deactivation",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}

try {

    Connection con = DBConnection.getConnection();

    String sql =
            "UPDATE users SET account_status='Inactive' "
            + "WHERE user_id=? AND role='Student'";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1, userId);

    pst.executeUpdate();

    pst.close();
    con.close();

    JOptionPane.showMessageDialog(
            this,
            "Student account deactivated."
    );

    loadUsers();

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       AdminDashboard admin = new AdminDashboard();
admin.setLocationRelativeTo(null);
admin.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JButton btnReactivate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSuspend;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
