/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ewu.event.system;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ResetRequests extends javax.swing.JFrame {

    /**
     * Creates new form ResetRequests
     */
  public ResetRequests() {
    setContentPane(new BackgroundPanel());
initComponents();
    setSize(900, 600);
    setLocationRelativeTo(null);
    setResizable(false);

    loadRequests();
}
private void loadRequests() {

    DefaultTableModel model =
            (DefaultTableModel) tblRequests.getModel();

    model.setRowCount(0);

    String sql =
            "SELECT pr.request_id, "
            + "u.user_id, "
            + "u.name, "
            + "u.student_id, "
            + "u.email, "
            + "pr.request_date, "
            + "pr.status "
            + "FROM password_reset_requests pr "
            + "JOIN users u ON pr.user_id = u.user_id "
            + "ORDER BY pr.request_date DESC";

    try {

        Connection con = DBConnection.getConnection();

        if (con == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Database connection failed."
            );

            return;
        }

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs =
                pst.executeQuery();

        while (rs.next()) {

            Object[] row = {
                rs.getInt("request_id"),
                rs.getInt("user_id"),
                rs.getString("name"),
                rs.getString("student_id"),
                rs.getString("email"),
                rs.getTimestamp("request_date"),
                rs.getString("status")
            };

            model.addRow(row);
        }

        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error loading reset requests: "
                + e.getMessage()
        );

        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PASSWORD RESET REQUESTS");

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID ", "User ID ", "Student Name ", "Student ID ", "Email", "Request Date ", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequests);

        btnApprove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnApprove.setText("APPROVE");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReject.setText("REJECT ");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(btnApprove)
                        .addGap(39, 39, 39)
                        .addComponent(btnReject)
                        .addGap(29, 29, 29)
                        .addComponent(btnBack)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject)
                    .addComponent(btnBack))
                .addGap(181, 181, 181))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      AdminDashboard admin =
        new AdminDashboard();

admin.setLocationRelativeTo(null);
admin.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
       int row = tblRequests.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(
            this,
            "Please select a reset request first."
    );
    return;
}

int requestId = Integer.parseInt(
        tblRequests.getValueAt(row, 0).toString()
);

String status =
        tblRequests.getValueAt(row, 6).toString();

if (!status.equalsIgnoreCase("Pending")) {
    JOptionPane.showMessageDialog(
            this,
            "Only Pending requests can be approved."
    );
    return;
}

int confirm = JOptionPane.showConfirmDialog(
        this,
        "Approve this password reset request?",
        "Confirm Approval",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}

try {

    Connection con = DBConnection.getConnection();

    String sql =
            "UPDATE password_reset_requests "
            + "SET status='Approved', "
            + "approved_by=?, "
            + "approved_date=NOW() "
            + "WHERE request_id=? "
            + "AND status='Pending'";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1, Session.userId);
    pst.setInt(2, requestId);

    int rows = pst.executeUpdate();

    pst.close();
    con.close();

    if (rows > 0) {

        JOptionPane.showMessageDialog(
                this,
                "Password reset request approved."
        );

        loadRequests();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Request could not be approved."
        );
    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        int row = tblRequests.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(
            this,
            "Please select a reset request first."
    );
    return;
}

int requestId = Integer.parseInt(
        tblRequests.getValueAt(row, 0).toString()
);

String status =
        tblRequests.getValueAt(row, 6).toString();

if (!status.equalsIgnoreCase("Pending")) {
    JOptionPane.showMessageDialog(
            this,
            "Only Pending requests can be rejected."
    );
    return;
}

int confirm = JOptionPane.showConfirmDialog(
        this,
        "Reject this password reset request?",
        "Confirm Rejection",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}

try {

    Connection con = DBConnection.getConnection();

    String sql =
            "UPDATE password_reset_requests "
            + "SET status='Rejected', "
            + "approved_by=?, "
            + "approved_date=NOW() "
            + "WHERE request_id=? "
            + "AND status='Pending'";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1, Session.userId);
    pst.setInt(2, requestId);

    int rows = pst.executeUpdate();

    pst.close();
    con.close();

    if (rows > 0) {

        JOptionPane.showMessageDialog(
                this,
                "Password reset request rejected."
        );

        loadRequests();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Request could not be rejected."
        );
    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnRejectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetRequests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequests;
    // End of variables declaration//GEN-END:variables
}
