/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ewu.event.system;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class ResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassword
     */
    public ResetPassword() {
   setContentPane(new BackgroundPanel());
initComponents();
    setSize(900, 600);
    setLocationRelativeTo(null);
    setResizable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        chkShowPasswords = new javax.swing.JCheckBox();
        btnResetPassword = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reset Password");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID;");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registered Email:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password:");

        txtStudentId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIdActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        chkShowPasswords.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkShowPasswords.setForeground(new java.awt.Color(255, 255, 255));
        chkShowPasswords.setText("Show Passwords");
        chkShowPasswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPasswordsActionPerformed(evt);
            }
        });

        btnResetPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnResetPassword.setText("RESET PASSWORD ");
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("BACK TO LOGIN");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnResetPassword)
                        .addGap(77, 77, 77)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                                    .addComponent(txtStudentId)
                                    .addComponent(txtEmail)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(608, 608, 608)
                        .addComponent(chkShowPasswords))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap(1092, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(chkShowPasswords)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetPassword)
                    .addComponent(btnBack))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdActionPerformed

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
        String studentId = txtStudentId.getText().trim();
String email = txtEmail.getText().trim().toLowerCase();

String newPassword =
        new String(txtNewPassword.getPassword());

String confirmPassword =
        new String(txtConfirmPassword.getPassword());


// REQUIRED FIELDS
if (studentId.isEmpty()
        || email.isEmpty()
        || newPassword.isEmpty()
        || confirmPassword.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Please fill in all fields."
    );

    return;
}


// STUDENT ID FORMAT
if (!studentId.matches("\\d{4}-\\d-\\d{2}-\\d{3}")) {

    JOptionPane.showMessageDialog(
            this,
            "Invalid Student ID format.\n"
            + "Example: 2024-3-60-308"
    );

    return;
}


// PASSWORD LENGTH
if (newPassword.length() < 8) {

    JOptionPane.showMessageDialog(
            this,
            "Password must contain at least 8 characters."
    );

    return;
}


// LETTER + NUMBER RULE
if (!newPassword.matches(".*[A-Za-z].*")
        || !newPassword.matches(".*\\d.*")) {

    JOptionPane.showMessageDialog(
            this,
            "Password must contain at least one letter and one number."
    );

    return;
}


// CONFIRM PASSWORD
if (!newPassword.equals(confirmPassword)) {

    JOptionPane.showMessageDialog(
            this,
            "Passwords do not match."
    );

    return;
}


Connection con = null;

try {

    con = DBConnection.getConnection();

    if (con == null) {

        JOptionPane.showMessageDialog(
                this,
                "Database connection failed."
        );

        return;
    }


    // FIND AN APPROVED REQUEST FOR THIS EXACT STUDENT
    String checkSql =
            "SELECT u.user_id, pr.request_id "
            + "FROM users u "
            + "JOIN password_reset_requests pr "
            + "ON u.user_id = pr.user_id "
            + "WHERE u.student_id=? "
            + "AND u.email=? "
            + "AND u.role='Student' "
            + "AND u.account_status <> 'Inactive' "
            + "AND pr.status='Approved' "
            + "ORDER BY pr.approved_date DESC "
            + "LIMIT 1";

    PreparedStatement check =
            con.prepareStatement(checkSql);

    check.setString(1, studentId);
    check.setString(2, email);

    ResultSet rs =
            check.executeQuery();


    if (!rs.next()) {

        JOptionPane.showMessageDialog(
                this,
                "No approved password reset request was found.\n"
                + "Please submit a request and wait for administrator approval."
        );

        rs.close();
        check.close();
        con.close();

        return;
    }


    int userId = rs.getInt("user_id");
    int requestId = rs.getInt("request_id");

    rs.close();
    check.close();


    // START TRANSACTION
    con.setAutoCommit(false);


    // CHANGE PASSWORD
    String updatePasswordSql =
            "UPDATE users "
            + "SET password=? "
            + "WHERE user_id=?";

    PreparedStatement updatePassword =
            con.prepareStatement(updatePasswordSql);

    updatePassword.setString(1, newPassword);
    updatePassword.setInt(2, userId);

    int passwordRows =
            updatePassword.executeUpdate();

    updatePassword.close();


    // MARK RESET REQUEST AS COMPLETED
    String completeSql =
            "UPDATE password_reset_requests "
            + "SET status='Completed' "
            + "WHERE request_id=? "
            + "AND status='Approved'";

    PreparedStatement complete =
            con.prepareStatement(completeSql);

    complete.setInt(1, requestId);

    int requestRows =
            complete.executeUpdate();

    complete.close();


    if (passwordRows == 1 && requestRows == 1) {

        con.commit();

        JOptionPane.showMessageDialog(
                this,
                "Password Reset Successful!\n"
                + "You can now login using your new password."
        );

        LoginForm login = new LoginForm();
        login.setLocationRelativeTo(null);
        login.setVisible(true);

        this.dispose();

    } else {

        con.rollback();

        JOptionPane.showMessageDialog(
                this,
                "Password reset could not be completed."
        );
    }


    con.setAutoCommit(true);
    con.close();


} catch (Exception e) {

    try {

        if (con != null) {
            con.rollback();
            con.close();
        }

    } catch (Exception ignored) {
    }

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage()
    );

    e.printStackTrace();
}
    }//GEN-LAST:event_btnResetPasswordActionPerformed

    private void chkShowPasswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordsActionPerformed
       if (chkShowPasswords.isSelected()) {

    txtNewPassword.setEchoChar((char) 0);
    txtConfirmPassword.setEchoChar((char) 0);

} else {

    txtNewPassword.setEchoChar('*');
    txtConfirmPassword.setEchoChar('*');
}
    }//GEN-LAST:event_chkShowPasswordsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       LoginForm login = new LoginForm();
login.setLocationRelativeTo(null);
login.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JCheckBox chkShowPasswords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
